### ISSUE TITLE
asa_ogs KeyError Exception on Empty Object-Group

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.asa#124]
##### SUMMARY

When a network object-group exists but does not contain any network-object's you get a KeyError on 'network-object' that is not caught. This configuration is valid in the ASA so it should be handled.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
/home/darkhelmet/.venvs/py2-ansible2.9/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
ansible 2.9.23
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/darkhelmet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/darkhelmet/.venvs/py2-ansible2.9/lib/python2.7/site-packages/ansible
  executable location = /home/darkhelmet/.venvs/py2-ansible2.9/bin/ansible
  python version = 2.7.18 (default, May 19 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
```
Same problem with Ansible 2.9.23 on Python 3.9 as well.

##### COLLECTION VERSION

```paste below
# /home/darkhelmet/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.asa  2.0.2  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

ASA 9.12(4)29 on both real hardware and an ASAv

##### STEPS TO REPRODUCE

Create an empty network object-group but do not add any network-objects to it. You will get a KeyError on network-object missing because no network-object's are in the object-group.

```
object-group network bug_test_obj
```

```yaml
---
- hosts: all
  tasks:
    - cisco.asa.asa_ogs:
        config:
          - object_type: network
            object_groups:
              - name: bug_test_obj
                network_object:
                  host:
                    - 9.9.9.9
```

##### EXPECTED RESULTS

The empty object-group now has 9.9.9.9 instead of being empty.

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/darkhelmet/.ansible/tmp/ansible-local-80877k3oz87/ansible-tmp-1629468497.24-80940-60367002611697/AnsiballZ_asa_ogs.py", line 102, in <module>
    _ansiballz_main()
  File "/home/darkhelmet/.ansible/tmp/ansible-local-80877k3oz87/ansible-tmp-1629468497.24-80940-60367002611697/AnsiballZ_asa_ogs.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/darkhelmet/.ansible/tmp/ansible-local-80877k3oz87/ansible-tmp-1629468497.24-80940-60367002611697/AnsiballZ_asa_ogs.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_ogs', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_ogs.py", line 918, in <module>
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_ogs.py", line 912, in main
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/ogs/ogs.py", line 56, in execute_module
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/ogs/ogs.py", line 129, in gen_config
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/ogs/ogs.py", line 145, in _compare
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/ogs/ogs.py", line 221, in _network_object_compare
  File "/tmp/ansible_cisco.asa.asa_ogs_payload_pfeq4xn0/ansible_cisco.asa.asa_ogs_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/ogs/ogs.py", line 474, in _add_object_cmd
KeyError: 'network_object'
```

@nj344170w and @russ-jenkins

**Comment by justjais** [comment]
@timway Thanks for raising the issue, I've raised a PR with the fix, and if feasible plz verify if the PR fix resolves the issue you're facing.
