### ISSUE TITLE
Error when using "any" as source or destination in asa_acls playbook

### ISSUE THREAD

**Issue by busseax** [ansible-collections/cisco.asa#39]
##### SUMMARY
Facing an error when trying to set a source or destination to any in playbook while using asa_acls module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
asa_acls

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abusse/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_legacy_silent
```

##### OS / ENVIRONMENT
Debian 10.4
ASA is running version 9.9(1)2

##### STEPS TO REPRODUCE

Collections used:
```
ansible.netcommon:0.0.3-dev51
cisco.asa:0.0.2-dev15
```

Playbook used:
```yaml
---
- hosts: devpn

  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable
  vars_files:
    - ./credentials.yml

  collections:
    - cisco.asa

  tasks:
    - name: "TASK 1: Create ansible_test ACL"
      asa_acls: &id001
        config:
          - acls:
            - name: ansible_test
              acl_type: extended
              aces:
                - remark: HostA
                - grant: permit
                  protocol: ip
                  source:
                    host: 1.1.1.1
                  destination:
                    any: true
                - remark: HostB
                - grant: permit
                  protocol: ip
                  source:
                    host: 2.2.2.2
                  destination:
                    any: true
                - remark: HostC
                - grant: permit
                  protocol: ip
                  source:
                    host: 3.3.3.3
                  destination:
                    any: true
        state: replaced
```

##### EXPECTED RESULTS

The output below should be the result on the ASA.
```
devpn# sh run access-list ansible_test
access-list ansible_test remark HostA
access-list ansible_test extended permit ip host 1.1.1.1 any
access-list ansible_test remark HostB
access-list ansible_test extended permit ip host 2.2.2.2 any
access-list ansible_test remark HostC
access-list ansible_test extended permit ip host 3.3.3.3 any
```

##### ACTUAL RESULTS

```
$ ansible-playbook --ask-vault-pass --check -i staging acl.yml -v
Using /etc/ansible/ansible.cfg as config file
Vault password:

PLAY [devpn] ******************************************************************************************************************************************************

TASK [TASK 1: Create ansible_test ACL] ****************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: 'any' is not in list
fatal: [devpn]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/abusse/.ansible/tmp/ansible-local-15293098Y72/ansible-tmp-1591790115.48-15300-4341809460479/AnsiballZ_asa_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/abusse/.ansible/tmp/ansible-local-15293098Y72/ansible-tmp-1591790115.48-15300-4341809460479/AnsiballZ_asa_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/abusse/.ansible/tmp/ansible-local-15293098Y72/ansible-tmp-1591790115.48-15300-4341809460479/AnsiballZ_asa_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python2.7/runpy.py", line 188, in run_module
        fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1194, in <module>
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1189, in main
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 71, in execute_module
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 53, in get_acls_facts
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/facts.py", line 60, in get_facts
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 70, in populate_facts
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 397, in render_config
      File "/tmp/ansible_asa_acls_payload_qAh3jF/ansible_asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/facts/acls/acls.py", line 193, in populate_source_destination
    ValueError: 'any' is not in list
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ********************************************************************************************************************************************************
devpn                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by justjais** [comment]
@busseax Thanks for raising the issue, I have raised a PR #41 to fix the issue, thus closing the issue.

**Comment by busseax** [comment]
@justjais Sorry for the late reply but I just tested the same playbook with the latest Ansible version (2.9.10) and the latest version of both the cisco.asa and netcommon collection from Ansible Galaxy. The error is still the same: `ValueError: 'any' is not in list`.

Let me know what other information you need to reproduce this behavior.

**Comment by justjais** [comment]
@busseax Thank you for testing the asa acls resource and I believe you're seeing the similar issue what's raised under https://github.com/ansible-collections/cisco.asa/issues/56, currently `any4/any6` for `ipv/v6` is not supported under source and destination. I'll raise a PR to include the respective feature asap. I'll be updating the respective PR for tracking.

**Comment by busseax** [comment]
@justjais Thanks for your feedback. I'm not using any4/any6 statements in my playbook. I just set `any: true` for the destination which isn't working.

**Comment by justjais** [comment]
@busseax ah that's strange then, as I have fixed the issue and have added the TC as well(ref: https://github.com/ansible-collections/cisco.asa/blob/main/tests/integration/targets/asa_acls/tests/cli/merged.yaml#L76) and for the ASA platform over which integration tests are running is passing. Can you plz check and verify if you're using the latest 1.0.0/1.0.1 ASA collections and also that your existing ASA config is not having any4/any6 in any of it's source/destination.

As the module gather facts first and then apply the play config, so execution will fail and give the said error if source/destination has any4/any6 pre-configured.

**Comment by busseax** [comment]
You were right, I the VPN appliance was configured with any4 values. However, I changed that to be just `any` but that didn't help to resolve the issue. 
My current ASA config is:
`sh run access-list ansible_test
access-list ansible_test remark HostA
access-list ansible_test extended permit ip host 1.1.1.1 any
access-list ansible_test remark HostB
access-list ansible_test extended permit ip host 2.2.2.2 any
access-list ansible_test remark HostC
access-list ansible_test extended permit ip host 3.3.3.3 any`

The playbook is still the same as in the bug report. However, I guess I now understand that when it's gathering the facts before applying the changes it's looking at the entire configuration, not just the parts I wanted to modify so there are indeed more places where we used `any4` values.

The collections I use are `ansible.netcommon 1.0.1-dev8` and `cisco.asa 1.0.1-dev3`.

**Comment by justjais** [comment]
@busseax Thanks for the update and yes, acl facts logic will gather the entire config and not just the config you want to update. I've started working on the implementation part of the issue, and I am hopeful that it should be done by max next week.
