### ISSUE TITLE
state: merged fails on standard ACL creation

### ISSUE THREAD

**Issue by omegafoo** [ansible-collections/cisco.asa#79]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.asa.asa_acls

##### ANSIBLE VERSION

```paste below
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```
##### ANSIBLE COLLECTION VERSION
```json
{
 "collection_info": {
  "namespace": "cisco",
  "name": "asa",
  "version": "1.0.3",
  "authors": [
   "Ansible Security Community (ansible-security)"
  ],
  "readme": "README.md",
  "tags": [
   "cisco",
   "asa",
   "networking",
   "security"
  ],
  "description": "Ansible Security Collection for Cisco ASA devices.",
  "license": [],
  "license_file": "LICENSE",
  "dependencies": {
   "ansible.netcommon": "*"
  },
  "repository": "https://github.com/ansible-collections/cisco.asa",
  "documentation": null,
  "homepage": null,
  "issues": null
 },
 "file_manifest_file": {
  "name": "FILES.json",
  "ftype": "file",
  "chksum_type": "sha256",
  "chksum_sha256": "a6419bbb09c3eae9741a5fab9efe4b35c43990b1d5b327b872509cbb1ab35b68",
  "format": 1
 },
 "format": 1
}
```
##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TERMINAL_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/terminal', '/etc/ansible/plugins/terminal']
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux release 8.2 (Ootpa)
Cisco ASA 5525X running ASA code 9.4(4)37

##### STEPS TO REPRODUCE

This is an attempt to add a new standard ACL to a Cisco ASA 5525X

```yaml
# Configure Test ACL
- name: test acl
  cisco.asa.asa_acls:
    config:
      - acls:
        - name: test_temp
          acl_type: standard
          aces:
          - grant: permit
            source:
              host: 10.1.1.1
            line: 1
     state: merged
```
The documentation isn't clear as to whether a standard ACL should be done with source or destination host/prefix and I have tried both with the same results when attempting to generate a standard acl

```yaml
# Configure Test ACL
- name: test acl
  cisco.asa.asa_acls:
    config:
      - acls:
        - name: test_temp
          acl_type: standard
          aces:
          - grant: permit
            destination:
              host: 10.1.1.1
            line: 1
     state: merged
```

##### EXPECTED RESULTS

This should generate a new access-list formatted as:

```
access-list test_temp standard permit host 10.1.1.1
```

##### ACTUAL RESULTS

Got a traceback error for acl configuration

```paste below
ansible-playbook 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/inventory/bes as it did not pass its verify_file() method
script declined parsing /etc/ansible/inventory/bes as it did not pass its verify_file() method
auto declined parsing /etc/ansible/inventory/bes as it did not pass its verify_file() method
Parsed /etc/ansible/inventory/bes inventory source with ini plugin
setting up inventory plugins
host_list declined parsing /etc/ansible/inventory/firewalls as it did not pass its verify_file() method
script declined parsing /etc/ansible/inventory/firewalls as it did not pass its verify_file() method
auto declined parsing /etc/ansible/inventory/firewalls as it did not pass its verify_file() method
Parsed /etc/ansible/inventory/firewalls inventory source with ini plugin
setting up inventory plugins
host_list declined parsing /etc/ansible/inventory/routers as it did not pass its verify_file() method
script declined parsing /etc/ansible/inventory/routers as it did not pass its verify_file() method
auto declined parsing /etc/ansible/inventory/routers as it did not pass its verify_file() method
Parsed /etc/ansible/inventory/routers inventory source with ini plugin
Trying secret FileVaultSecret(filename='/home/user/.ansible/.vault-pass.user') for vault_id=user
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
Trying secret FileVaultSecret(filename='/home/user/.ansible/.vault-pass.user') for vault_id=user
Tried to use the vault secret (user) to decrypt (/etc/ansible/roles/vpn_anyconnect/vars/main/vpn_vault.yml) but it failed. Error: HMAC verification failed: Signature did not match digest.
Trying secret FileVaultSecret(filename='/home/user/.ansible/.vault-pass.vpn') for vault_id=vpn
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
statically imported: /etc/ansible/roles/vpn_anyconnect/tasks/anyconnect_image.yml
Loading callback plugin yaml of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/yaml.py

PLAYBOOK: vpn.yml ***************************************************************************************************************************************************************************************************************************************
Positional arguments: /etc/ansible/playbooks/cisco/vpn.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/inventory',)
subset: fw-test
vault_ids: ('user@~/.ansible/.vault-pass.user', 'vpn@~/.ansible/.vault-pass.vpn')
forks: 5
1 plays in /etc/ansible/playbooks/cisco/vpn.yml
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'

PLAY [Configure Test firewall] ***********************************************************************************************************************************************************************************************************************
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
<fw-test> attempting to start connection
<fw-test> using connection plugin ansible.netcommon.network_cli
<fw-test> local domain socket does not exist, starting it
<fw-test> control socket path is /home/user/.ansible/pc/dca9d2a8b8
<fw-test> local domain socket listeners started successfully
<fw-test> loaded cliconf plugin ansible_collections.cisco.asa.plugins.cliconf.asa from path /usr/share/ansible/collections/ansible_collections/cisco/asa/plugins/cliconf/asa.py for network_os cisco.asa.asa
<fw-test> 
<fw-test> local domain socket path is /home/user/.ansible/pc/dca9d2a8b8
[WARNING]: Ignoring timeout(10) for cisco.asa.asa_facts
<fw-test> ESTABLISH LOCAL CONNECTION FOR USER: user
<fw-test> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161 `" && echo ansible-tmp-1605644961.43957-1819730-200278910582161="` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161 `" ) && sleep 0'
<fw-test> Attempting python interpreter discovery
<fw-test> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<fw-test> EXEC /bin/sh -c '/usr/bin/python3.6 && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/cisco/asa/plugins/modules/asa_facts.py
<fw-test> PUT /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/tmpg6g55mza TO /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161/AnsiballZ_asa_facts.py
<fw-test> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161/ /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161/AnsiballZ_asa_facts.py && sleep 0'
<fw-test> EXEC /bin/sh -c '/usr/libexec/platform-python /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161/AnsiballZ_asa_facts.py && sleep 0'
<fw-test> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644961.43957-1819730-200278910582161/ > /dev/null 2>&1 && sleep 0'

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/cisco/vpn.yml:2
ok: [fw-test]
META: ran handlers
Read vars_file '{{ lookup('ansible.builtin.env', 'HOME') }}/.ansible/myvault.yml'
<fw-test> attempting to start connection
<fw-test> using connection plugin ansible.netcommon.network_cli
<fw-test> found existing local domain socket, using it!
<fw-test> invoked shell using ssh_type: paramiko
<fw-test> ssh type is set to paramiko
<fw-test> ssh connection done, setting terminal
<fw-test> loaded terminal plugin for network_os cisco.asa.asa
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> firing event: on_become
<fw-test> firing event: on_open_shell()
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> ssh connection has completed successfully
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<fw-test> updating play_context for connection
<fw-test> 
<fw-test> local domain socket path is /home/user/.ansible/pc/dca9d2a8b8
<fw-test> ESTABLISH LOCAL CONNECTION FOR USER: user
<fw-test> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276 `" && echo ansible-tmp-1605644964.7193863-1819769-138475429746276="` echo /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276 `" ) && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/cisco/asa/plugins/modules/asa_acls.py
<fw-test> PUT /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/tmp99tka15l TO /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py
<fw-test> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/ /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py && sleep 0'
<fw-test> EXEC /bin/sh -c '/usr/libexec/platform-python /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py && sleep 0'
<fw-test> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/ > /dev/null 2>&1 && sleep 0'

TASK [vpn_anyconnect : Configure split tunnel ACLs] *****************************************************************************************************************************************************************************************************
task path: /etc/ansible/roles/vpn_anyconnect/tasks/main.yml:13
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1238, in <module>
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1233, in main
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 77, in execute_module
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 121, in set_config
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 150, in set_state
  File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 390, in _state_merged
TypeError: 'NoneType' object is not iterable
fatal: [fw-test]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 102, in <module>
        _ansiballz_main()
      File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/user/.ansible/tmp/ansible-local-1819723jy3tqp7z/ansible-tmp-1605644964.7193863-1819769-138475429746276/AnsiballZ_asa_acls.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.asa.plugins.modules.asa_acls', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1238, in <module>
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/modules/asa_acls.py", line 1233, in main
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 77, in execute_module
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 121, in set_config
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 150, in set_state
      File "/tmp/ansible_cisco.asa.asa_acls_payload_u_0iiuyy/ansible_cisco.asa.asa_acls_payload.zip/ansible_collections/cisco/asa/plugins/module_utils/network/asa/config/acls/acls.py", line 390, in _state_merged
    TypeError: 'NoneType' object is not iterable
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
fw-test        : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

**Comment by justjais** [comment]
@omegafoo can you plz verify with the `1.0.4` release if you're still facing the same issue, as I've updated `asa_acls` module fixing the code design.

**Comment by omegafoo** [comment]
This appears to now be working correctly. I believe you can close out this issue are resolved.

**Comment by justjais** [comment]
@omegafoo thanks so much for confirming the same.
